service: hitmans

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  stage: ${opt:stage, 'dev'}

layers:
  hitmansReqs:
    path: layers/reqs
    description: "Dependencies for projectName"
    compatibleRuntime:
      - python3.8

package:
  individually: true
  exclude:
    - venv/**
    - test/**
    - node_modules/**

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  login:
    handler: src/handlers/users.login
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: post
          path: users/login

  logout:
    handler: src/handlers/users.logout
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: post
          path: users/logout

  register:
    handler: src/handlers/users.register
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: post
          path: users

  list_users:
    handler: src/handlers/users.list_users
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: get
          path: users

  fetch_user:
    handler: src/handlers/users.fetch_user
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: get
          path: users/{user_id}

  assign_hitman_manager:
    handler: src/handlers/users.assign_manager
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: put
          path: users/{user_id}/manager

  deactivate_user:
    handler: src/handlers/users.deactivate
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: put
          path: users/{user_id}/deactivate

  list_hits:
    handler: src/handlers/hits.list_hits
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: get
          path: hits

  create_hit:
    handler: src/handlers/hits.create
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: post
          path: hits

  fetch_hit:
    handler: src/handlers/hits.fetch_hit
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: get
          path: hits/{hit_id}

  assign_hit:
    handler: src/handlers/hits.assign_hit
    layers:
      - {Ref: HitmansReqsLambdaLayer}
    events:
      - http:
          method: put
          path: hits/{hit_id}


plugins:
  - serverless-python-requirements
  - serverless-offline
