app_name: "hitmans"

database: "mongodb+srv://hitman:swfpxMoz2qUD3FTA@hitmans.xyb5a.mongodb.net/hitmans?retryWrites=true&w=majority"

master_user: "5f3f4d6946d75e60d731f1f8"

salt: "$2b$12$xWiFaDEF4pWddBgPRr.hFu"

jwt:
  secret: "jkbr72bndf81n"
  algorithm: "HS256"

